personal_portfolio_project/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='blog'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

personal_portfolio_project/personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

personal_portfolio_project/blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=200)
    date = models.DateField(auto_now_add=True)
    text = models.TextField()

    def __str__(self):
        return self.title

personal_portfolio_project/portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    desc = models.CharField(max_length=250)
    img = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

personal_portfolio_project/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

def all_blogs(request):
    blogs = Blog.objects.all()
    return render(request, 'blog/all_blogs.html', {'blogs': blogs})

def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

personal_portfolio_project/portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/home.html', {'projects': projects})

personal_portfolio_project/blog/templates/blog/all_blogs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
</head>
<body>
    <h1>Blog</h1>
    <h2>Valera was written {{ blogs.count }} state{{ blogs.count|pluralize }}</h2>

    {% for blog in blogs %}
    <a href="{% url 'blog:detail' blog.id %}">{{ blog.title }}</a>
    <br>
    {{ blog.date|date:'M d Y' }}
    <br>
    {{ blog.text|truncatechars:10 }}
    <br>
    {% endfor %}

</body>
</html>

personal_portfolio_project/blog/templates/blog/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{ blog.title }}</h1>
    <h2>--{{ blog.date|date:'F jS Y' }}--</h2>
    <p>{{ blog.text|safe }}</p>
</body>
</html>

personal_portfolio_project/portfolio/templates/portfolio/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio</title>
</head>
<body>
    <h1>This is my portfolio!</h1>

    <a href="{% url 'blog:blog' %}">Blog</a><br>

    {% load static %}

    <img src="{% static 'portfolio/photo.jpg' %}" width="200"><br>
    <a href="{% static 'portfolio/cert-253460.pdf' %}">Certificate</a><br>

    {% for project in projects %}
    {{ project.title }}
    <br>
    {{ project.desc }}
    <br>
    <img src="{{ project.img.url }}" alt="" height="100">
    <br>
    {% if project.url %}
    <a href="{{ project.url }}">Link</a>
    {% endif %}
    <br>
    {% endfor %}
</body>
</html>